services:
  db:
    image: postgres:16-alpine
    container_name: appointment-db
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d # Executa o init.sql ao iniciar

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: appointment-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appointment_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      db:
        condition: service_healthy