
ALTER TABLE professionals ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE services ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE clients ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE appointments ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE professionals SET active = TRUE WHERE active IS NULL;
UPDATE services SET active = TRUE WHERE active IS NULL;